seed: 123 # this will be the seed for the whole project

# Project Colors
color1: "#62b6cb"
color2: "#fb8500"
color3: "#023047"
color4: "#FFB703"

# paths
path_annotations: "./Data"
path_train: "./Data/train/original"
path_train_train: "./Data/train/train"
path_train_aug: "./Data/train/train_aug"
path_train_val: "./Data/train/val"
path_test: "./Data/test"
path_yolo : "./Data/Yoloimages/" # Images structured using Yolo format requirement 
path_models: "./Models"

# annotations names
kaggle_train_annotations : "annotations_train.json"
train_annotations_name_temp: "annotations_train_temp.json"
train_annotations_name : "annotations_train_updated.json"
aug_train_annotations_name: "annotations_train_updated_aug.json"
val_annotations_name : "annotations_val_updated.json"

kaggle_test_annotations : "annotations_test.json"
test_annotations_name_temp: "annotations_test_temp.json"
test_annotations_name : "annotations_test_updated.json"

weights_yolo_path : 'Models/yolo_weights'
runs_path: 'Models/runs'

# AWS S3 bucket names
bucket_name: "sagemaker-eu-west-1-project-danielteresa/"
bucket_name2: "sagemaker-eu-west-1-project-danielteresa"

# models names to be saved in S3
# this should be the structure: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,31}

tuning_jobname: "YOLO-tuning7"
final_jobname:  "YOLO-final2"





