seed: 123 # this will be the seed for the whole project

# Project Colors
color1: "#62b6cb"
color2: "#fb8500"

# paths
path_annotations: "./Data"
path_train: "./Data/train/original"
path_train_train: "./Data/train/train"
path_train_aug: "./Data/train/train_aug"
path_train_val: "./Data/train/val"
path_test: "./Data/test"

# annotations names
kaggle_train_annotations : "annotations_train.json"
train_annotations_name_temp: "annotations_train_temp.json"
train_annotations_name : "annotations_train_updated.json"
aug_train_annotations_name: "annotations_train_updated_aug.json"
val_annotations_name : "annotations_val_updated.json"

kaggle_test_annotations : "annotations_test.json"
test_annotations_name_temp: "annotations_test_temp.json"
test_annotations_name : "annotations_test_updated.json"






path_yolo : "./Data/Yoloimages/" # Images structured using Yolo format requirement 



weights_yolo_path : './yolo_weights'

aux_trainaug_folder : './CustomImages/aux_trainaug/'
aux_train_folder : './CustomImages/aux_train/'
aux_val_folder : './CustomImages/aux_val/'
coco_to_yolo_folder : 'labels/annotations'
